// ===== 阅读器设置管理 =====
import { createApp, ref, toRaw } from 'vue'
import { MotionPlugin } from '@vueuse/motion'
import { Dialog, showMessage, fetchSyncPost } from 'siyuan'
import type { Plugin } from 'siyuan'
import SettingsVue from '@/components/Settings.vue'

export type PageAnimation = 'slide' | 'scroll' | 'none'
export type ColumnMode = 'single' | 'double'
export type TocPosition = 'left' | 'right'
export type DocInfo = { id: string; name: string; path: string; notebook: string }
export interface ReadTheme { name: string; color: string; bg: string; bgImg?: string }
export interface FontFileInfo { name: string; displayName: string }
export interface TextSettings { fontFamily: string; fontSize: number; letterSpacing: number; customFont: { fontFamily: string; fontFile: string } }
export interface ParagraphSettings { lineHeight: number; paragraphSpacing: number; textIndent: number }
export interface LayoutSettings { marginHorizontal: number; marginVertical: number; gap: number; headerFooterMargin: number; maxBlockSize: number }
export interface VisualSettings { brightness: number; contrast: number; sepia: number; saturate: number; invert: boolean }
export interface ReaderSettings { enabled: boolean; openMode: 'newTab' | 'rightTab' | 'bottomTab' | 'newWindow'; tocPosition: TocPosition; pageAnimation: PageAnimation; columnMode: ColumnMode; theme: string; customTheme: ReadTheme; annotationMode: 'notebook' | 'document'; notebookId?: string; parentDoc?: DocInfo; textSettings: TextSettings; paragraphSettings: ParagraphSettings; layoutSettings: LayoutSettings; visualSettings: VisualSettings }

// ===== 预设主题 =====
export const PRESET_THEMES: Record<string, ReadTheme> = { default: { name: 'themeDefault', color: '#202124', bg: '#ffffff' }, almond: { name: 'themeAlmond', color: '#414441', bg: '#FAF9DE' }, autumn: { name: 'themeAutumn', color: '#414441', bg: '#FFF2E2' }, green: { name: 'themeGreen', color: '#414441', bg: '#E3EDCD' }, blue: { name: 'themeBlue', color: '#414441', bg: '#DCE2F1' }, night: { name: 'themeNight', color: '#fff6e6', bg: '#415062' }, dark: { name: 'themeDark', color: '#d5cecd', bg: '#414441' }, gold: { name: 'themeGold', color: '#b58931', bg: '#081010' } }

// ===== 工具函数 =====
const fixUrl = (url: string) => url.startsWith('http') || url.startsWith('/') ? url : `/${url}`
const msg = { success: (m: string) => showMessage(m, 2000, 'info'), error: (m: string) => showMessage(m, 3000, 'error') }

export const applyTheme = (el: HTMLElement, settings: ReaderSettings) => { const theme = settings.theme === 'custom' ? settings.customTheme : PRESET_THEMES[settings.theme]; if (!theme) return; const s = el.style, img = theme.bgImg; s.color = theme.color; s.backgroundColor = img ? 'transparent' : theme.bg; s.backgroundImage = img ? `url("${fixUrl(img)}")` : ''; s.backgroundSize = img ? 'cover' : ''; s.backgroundPosition = img ? 'center' : ''; s.backgroundRepeat = img ? 'no-repeat' : '' }

export const applyPageStyles = (iframe: HTMLIFrameElement, settings: ReaderSettings) => { const doc = iframe.contentDocument; if (!doc?.body) return; const { textSettings: t, paragraphSettings: p, layoutSettings: l } = settings; doc.querySelectorAll('style[data-sireader-page]').forEach(s => s.remove()); const isCustom = t.fontFamily === 'custom' && t.customFont.fontFamily, font = isCustom ? `"${t.customFont.fontFamily}", sans-serif` : (t.fontFamily || 'inherit'), fontFace = isCustom ? `@font-face{font-family:"${t.customFont.fontFamily}";src:url("/plugins/custom-fonts/${t.customFont.fontFile}")}` : ''; doc.head.appendChild(Object.assign(doc.createElement('style'), { 'data-sireader-page': 'true', textContent: `${fontFace}body{font-family:${font}!important;font-size:${t.fontSize}px!important;letter-spacing:${t.letterSpacing}em!important;padding:${l.marginVertical}px ${l.marginHorizontal}px!important}p,div{line-height:${p.lineHeight}!important;margin:${p.paragraphSpacing}em 0!important}p{text-indent:${p.textIndent}em!important}` })) }

// ===== 默认配置 =====
const DEFAULT_SETTINGS: ReaderSettings = { enabled: true, openMode: 'newTab', tocPosition: 'left', pageAnimation: 'slide', columnMode: 'single', theme: 'default', customTheme: { name: 'custom', color: '#202124', bg: '#ffffff' }, annotationMode: 'notebook', notebookId: '', parentDoc: undefined, textSettings: { fontFamily: 'inherit', fontSize: 16, letterSpacing: 0, customFont: { fontFamily: '', fontFile: '' } }, paragraphSettings: { lineHeight: 1.6, paragraphSpacing: 0.8, textIndent: 0 }, layoutSettings: { marginHorizontal: 40, marginVertical: 20, gap: 5, headerFooterMargin: 0, maxBlockSize: 0 }, visualSettings: { brightness: 1, contrast: 1, sepia: 0, saturate: 1, invert: false } }

// ===== UI配置常量 =====
export const UI_CONFIG = { interfaceItems: [{ key: 'openMode', opts: ['newTab', 'rightTab', 'bottomTab', 'newWindow'] }, { key: 'tocPosition', opts: ['left', 'right'] }, { key: 'columnMode', opts: ['single', 'double'] }, { key: 'pageAnimation', opts: ['slide', 'scroll', 'none'] }], customThemeItems: [{ key: 'color', label: 'textColor', type: 'color' }, { key: 'bg', label: 'bgColor', type: 'color' }, { key: 'bgImg', label: 'bgImage', type: 'text' }], appearanceGroups: [{ title: 'textSettings', items: [{ key: 'fontSize', type: 'range', min: 12, max: 32, step: 1, unit: 'px' }, { key: 'letterSpacing', type: 'range', min: 0, max: 0.2, step: 0.01, unit: 'em' }] }, { title: 'paragraphSettings', items: [{ key: 'lineHeight', type: 'range', min: 1.0, max: 3.0, step: 0.1 }, { key: 'paragraphSpacing', type: 'range', min: 0, max: 2, step: 0.1, unit: 'em' }, { key: 'textIndent', type: 'range', min: 0, max: 4, step: 0.5, unit: 'em' }] }, { title: 'layoutSettings', items: [{ key: 'marginHorizontal', type: 'range', min: 0, max: 100, step: 5, unit: 'px' }, { key: 'marginVertical', type: 'range', min: 0, max: 80, step: 5, unit: 'px' }, { key: 'gap', type: 'range', min: 0, max: 20, step: 1, unit: '%' }, { key: 'headerFooterMargin', type: 'range', min: 0, max: 60, step: 5, unit: 'px' }, { key: 'maxBlockSize', type: 'range', min: 0, max: 1200, step: 50, unit: 'px' }] }, { title: 'visualSettings', items: [{ key: 'brightness', type: 'range', min: 0.5, max: 1.5, step: 0.05 }, { key: 'contrast', type: 'range', min: 0.5, max: 1.5, step: 0.05 }, { key: 'sepia', type: 'range', min: 0, max: 1, step: 0.05 }, { key: 'saturate', type: 'range', min: 0, max: 2, step: 0.1 }, { key: 'invert', type: 'checkbox' }] }] }

// ===== 字体管理 =====
export const scanCustomFonts = async (): Promise<FontFileInfo[]> => { try { const res = await fetchSyncPost('/api/file/readDir', { path: '/data/plugins/custom-fonts' }); return res?.code === 0 && Array.isArray(res.data) ? res.data.filter((f: any) => !f.isDir && /\.(ttf|otf|woff2?)$/i.test(f.name)).map((f: any) => ({ name: f.name, displayName: f.name.replace(/\.(ttf|otf|woff2?)$/i, '') })) : [] } catch { return [] } }
export const loadFonts = (fonts: FontFileInfo[]) => { let style = document.getElementById('sr-fonts'); if (!style) { style = document.createElement('style'); style.id = 'sr-fonts'; document.head.appendChild(style) }; style.textContent = fonts.map(f => `@font-face{font-family:"${f.displayName}";src:url("/plugins/custom-fonts/${f.name}")}`).join('') }
export const resetToDefaults = (settings: any) => (settings.textSettings = DEFAULT_SETTINGS.textSettings, settings.paragraphSettings = DEFAULT_SETTINGS.paragraphSettings, settings.layoutSettings = DEFAULT_SETTINGS.layoutSettings, settings.visualSettings = DEFAULT_SETTINGS.visualSettings)

// ===== 设置管理 =====
export function useSetting(plugin: Plugin) { const settings = ref<ReaderSettings>({ ...DEFAULT_SETTINGS }), i18n = plugin.i18n as any, customFonts = ref<FontFileInfo[]>([]), isLoadingFonts = ref(false); let dialog: Dialog | null = null, app: any = null; const load = async () => { const cfg = await plugin.loadData('config.json') || {}; cfg.settings && (settings.value = { ...DEFAULT_SETTINGS, ...cfg.settings }) }, save = async () => { try { const cfg = await plugin.loadData('config.json') || {}, raw = JSON.parse(JSON.stringify(toRaw(settings.value))); cfg.settings = raw; await plugin.saveData('config.json', cfg); window.dispatchEvent(new CustomEvent('sireaderSettingsUpdated', { detail: raw })); msg.success(i18n?.saved || '设置已保存') } catch (e) { msg.error(i18n?.saveError || '保存失败'); console.error('[SiReader]', e) } }, loadCustomFonts = async () => (isLoadingFonts.value = true, customFonts.value = await scanCustomFonts(), isLoadingFonts.value = false, loadFonts(customFonts.value)), setFont = (f?: FontFileInfo, onSave?: () => void) => (settings.value.textSettings.fontFamily = f ? 'custom' : 'inherit', f && (settings.value.textSettings.customFont = { fontFamily: f.displayName, fontFile: f.name }), onSave?.()), resetStyles = () => (resetToDefaults(settings.value), save()), open = async () => { dialog && (app?.unmount(), dialog.destroy()); await load(); dialog = new Dialog({ title: i18n?.settingsTitle || '设置', content: '<div id="sireader-settings-mount"></div>', width: '680px', height: '580px', destroyCallback: () => (app?.unmount(), dialog = null, app = null) }); const mountEl = dialog.element.querySelector('#sireader-settings-mount'); mountEl && (app = createApp(SettingsVue, { modelValue: settings.value, i18n, onSave: save, 'onUpdate:modelValue': (newSettings: ReaderSettings) => { settings.value = newSettings } }), app.use(MotionPlugin), app.mount(mountEl)) }; load(); return { settings, open, save, loadCustomFonts, setFont, resetStyles, customFonts, isLoadingFonts } }
